ARG EL_VERSION=9
FROM scratch as context

COPY --chmod=0775 system_files /files
COPY --chmod=0775 build_scripts /build_scripts

#FROM quay.io/centos-bootc/centos-bootc:stream${EL_VERSION}
FROM quay.io/centos-bootc/centos-bootc:sha256-7c4853aa5212a4eb77796d835701f84dffbf430ef904575df97b4b3f4988e4a4

COPY Justfile /Justfile

ARG EL_VERSION=9
ARG ARCH=x86_64
ARG ADMIN_USERNAME=starforge
ARG HARDENED=false
ARG BOOTLOADER_PASSWORD
ARG VARIANT=stock

ENV ARCH=${ARCH}
ENV EL_VERSION=${EL_VERSION}
ENV ADMIN_USERNAME=${ADMIN_USERNAME}
ENV HARDENED=${HARDENED}
ENV BOOTLOADER_PASSWORD=${BOOTLOADER_PASSWORD}
ENV VARIANT=${VARIANT}

# VARIANT postgres specific
ARG POSTGRESQL_USERNAME=postgres_user
ARG POSTGRESQL_MAJOR_VERSION=17
ARG POSTGRESQL_MINOR_VERSION=4
ARG DEFAULT_PASSWORD
ARG POSTGRESQL_REPLICATION_PASSWORD
ARG POSTGRES_EXPORTER_USER=postgres_exporter
ARG POSTGRES_EXPORTER_PASSWORD

ENV POSTGRESQL_USER=${POSTGRESQL_USER}
ENV POSTGRESQL_MAJOR_VERSION=${POSTGRESQL_MAJOR_VERSION}
ENV POSTGRESQL_MINOR_VERSION=${POSTGRESQL_MINOR_VERSION}
ENV POSTGRES_EXPORTER_USER=${POSTGRES_EXPORTER_USER}
ENV DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
ENV POSTGRES_EXPORTER_PASSWORD=${POSTGRES_EXPORTER_PASSWORD}
ENV POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD}


RUN \
#  --mount=type=tmpfs,dst=/opt \
 --mount=type=tmpfs,dst=/tmp \
 --mount=type=bind,from=context,source=/,target=/run/context \
 pwd && ls -la /run/context/build_scripts/ && \
 bash /run/context/build_scripts/build.sh
  
# for some reason centos-bootc doesn't have this as its entry point
ENTRYPOINT /sbin/init
